name: Daily Countdown # force trigger

on:
  schedule:
    - cron: '0 17 * * *'  # 00:00 giờ Việt Nam
  workflow_dispatch:

jobs:
  send_countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Send countdown message
        run: |
          DAY=$(date -u +"%Y-%m-%d")
          TARGET="2026-06-01"
          REMAIN=$(( ( $(date -d $TARGET +%s) - $(date -d $DAY +%s) ) / 86400 ))
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"Chỉ còn $REMAIN ngày nữa đến 1/6/2026!\"}" \
            https://discord.com/api/webhooks/xxxxx/xxxxx
