name: Daily Countdown

on:
  schedule:
    - cron: '0 17 * * *'  # 00:00 giờ Việt Nam hằng ngày
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -U discord.py

      - name: Run countdown bot
        env:
          DISCORD_TOKEN: ${{ secrets.BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python daily.py
